### ISSUE TITLE
Feature Request: HTML Output

### ISSUE THREAD

**Issue by HughxDev** [hoyois/html5outliner#2]
The similar [h5o](http://code.google.com/p/h5o/) project has an outline object method called `asHTML()` that outputs an ordered list of section titles, optionally as hyperlinks (using the section’s `id` or generating one if there’s none), that can be used to output a table of contents. I’d like to see that in this one. Right now I am using both scripts for their unique features, which means I incur a performance hit making the client download two separate scripts that do essentially the same thing, and then running them both.

**Comment by hoyois** [comment]
That's pretty much what my bookmarklet does on top of HTMLOutliner.js. Once you've run HTMLOutline(node), you can get a numbered table of contents using printOutline(node.sectionList):

https://github.com/hoyois/html5outliner/blob/master/bookmarklet.js#L166

That should be easily adaptable to your needs.

**Comment by HughxDev** [comment]
Oh, well that works. Thanks!
