### ISSUE TITLE
<main>-element not recognized

### ISSUE THREAD

**Issue by jensscherbl** [hoyois/html5outliner#4]
Keeping this up to date with the latest specs / drafts would be highly beneficial.

**Comment by jensscherbl** [comment]
Ah, sorry. Apparently, `<main>` isn't a [sectioning element](http://www.w3.org/html/wg/drafts/html/master/dom.html#sectioning-content-0). This stuff is so confusing...

**Comment by hoyois** [comment]
But I see they added `<dialog>` as a new sectioning root element. I'll review the spec and update...
