### ISSUE TITLE
First heading after subsection

### ISSUE THREAD

**Issue by unor** [hoyois/html5outliner#7]
If I’m not mistaken, I might have found a bug.

Take this document:

```
<body>
    <section>
      <nav></nav>
      <h1>Only heading</h1>
    </section>
</body>
```

The HTML5 Outliner produces this outline:

![html5-outliner_ex1](https://cloud.githubusercontent.com/assets/6901294/4227684/30168a0c-394a-11e4-92e1-c48e07aca0b0.png)

But I think this should be the correct outline:

![html5-outliner_ex2](https://cloud.githubusercontent.com/assets/6901294/4227685/37d24e70-394a-11e4-96fc-ef8a900a0a44.png)

The [current HTML5 CR says](http://www.w3.org/TR/2014/CR-html5-20140731/sections.html#headings-and-sections):

> The first element of heading content in an element of sectioning content represents the heading for that section.

So shouldn’t it use the `h1` as heading for the `section` even though this `h1` comes _after_ the `nav`?

---

I’m not sure what the correct behaviour is when this happens in the `body` sectioning root, e.g.:

```
<body>
  <nav></nav>
  <h1>Only Heading</h1>
</body>
```

The quoted spec explicitly mentions "in an element of sectioning content", so it doesn’t necessarily apply to sectioning root elements.

**Comment by hoyois** [comment]
The first outline is the correct one. When you enter nav, the section element acquires an "implied heading" so subsequent headings at that level will create new sections.

The text that you quote is wrong for more than one reason. For instance, a heading content element can be the first of its kind in several sectioning content elements.

**Comment by unor** [comment]
Ah right, thanks for the explanation :)

For others interested in this, the current spec even contains two [examples](http://www.w3.org/TR/2014/CR-html5-20140731/sections.html#sample-outlines) about this; the last two examples, prefaced with:
- "Headings never rise above other sections. […]"
- "Thus, when an `article` element starts with a `nav` block […]"
